language: node_js

node_js:
  - "7"

cache: yarn

jobs:
  include:
    - stage: deploy to production
      install: npm install -g now
      script: skip
      deploy:
        provider: script
        script: yarn now
        on:
          branch: master
