version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/project

  dependencies:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run: yarn install --pure-lockfile
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run: ls .
      - run: ls ./node_modules
      - run: yarn build


  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - run: sudo npm i -g now now-purge
      - run: which now-purge
      - run: which now
      - run: now-purge t $NOW_TOKEN
      - run: now -t $NOW_TOKEN deploy
      - run: now -t $NOW_TOKEN alias
      - run: now -t $NOW_TOKEN scale 1
      - run: now --debug

workflows:
  version: 2
  build:
    jobs:
      # Heat up the cache, git checkout will only happen once
      - checkout
      # Installing dependencies will only happen once
      - dependencies:
          requires:
            # Do not run 'dependencies' job before 'checkout' is done
            - checkout
      - test:
          requires:
            # Even though 'dependencies' already require 'checkout' it's
            # good practice to be explicit about what is required
            - checkout
            - dependencies
      - deploy:
          requires:
            - checkout
            # 'dependencies' is not needed, 'now.sh' will install dependencies
            - test
          filters:
            branches:
              only: master
