version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/project

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: node --version
      - run: git status
      - run: yarn install --pure-lockfile
      - run: git status

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sudo npm i -g now now-purge
      - run:
          name: Prevent breaching the max active instances on now
          command: now-purge t $NOW_TOKEN
      - run:
          name: Create new immutable now instance
          command: now -t $NOW_TOKEN deploy
      - run:
          name: Assign stipsan.me to the new now instance
          command: now -t $NOW_TOKEN alias
      - run:
          name: New instance must have at least 1 active instance
          command: now -t $NOW_TOKEN scale 1

workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
