version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: node --version
       - run: git status
       - run: yarn install --pure-lockfile
       - run: git status
       - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "deploy"
            fi
