version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: node --version
       - run: git status
       - run: yarn install --pure-lockfile
       - run: git status
       - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn global add now now-purge;
              now-purge t $NOW_TOKEN;
              now -t $NOW_TOKEN deploy;
              now -t $NOW_TOKEN alias;
              now -t $NOW_TOKEN scale 1;
            fi
